# Stubs for agate.aggregations (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

# from agate.aggregations.base import Aggregation
from agate.aggregations.max import Max
