# Stubs for agate.aggregations.base (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class Aggregation:
    def get_aggregate_data_type(self, table: Any) -> None: ...
    def validate(self, table: Any) -> None: ...
    def run(self, table: Any) -> None: ...
