# Stubs for agate.data_types.text (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from agate.data_types.base import DataType
from typing import Any

class Text(DataType):
    cast_nulls: Any = ...
    def __init__(self, cast_nulls: bool = ..., **kwargs: Any) -> None: ...
    def cast(self, d: Any): ...
