# Stubs for agate.data_types.time_delta (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from agate.data_types.base import DataType
from typing import Any

class TimeDelta(DataType):
    def cast(self, d: Any): ...
